import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Layout, Navbar } from "@/Components";
import Head from "next/head";
import { Context, StateContext } from "@/context/StateContext";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Abood eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout">
          <StateContext>
            <Head>
              <title>Abood eCommerce Web Site</title>
            </Head>
            <header>
              <Navbar />
            </header>
            <Toaster />
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </StateContext>
        </div>
      </body>
    </html>
  );
}
